micronaut:
  application:
    name: micronautdata-kt
  server:
     port : 8081
datasources:
  default:
    url: jdbc:mysql://localhost:3306/photo_app
    username: root
    password: password
    dialect: MYSQL

jpa:
  default:
    packages-to-scan:
      - 'com.tosh'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
